capp/users/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, BooleanField
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError
from capp.models import User


class RegistrationForm(FlaskForm):
  username = StringField('Username', 
                         validators=[DataRequired(), Length(min=2, max=30)])
  email = StringField('Email',
                      validators=[DataRequired(), Email()])
  password = PasswordField('Password', validators=[DataRequired()])
  confirm_password = PasswordField('Confirm Password',
                      validators=[DataRequired(), EqualTo('password')])                                
  submit = SubmitField('Sign Up')

  def validate_username(self, username):
        user = User.query.filter_by(username=username.data).first()
        if user:
            raise ValidationError('That username is taken. Please choose a different one.')

  def validate_email(self, email):
      user = User.query.filter_by(email=email.data).first()
      if user:
          raise ValidationError('That email is taken. Please choose a different one.')

class LoginForm(FlaskForm):
  email = StringField('Email',
                      validators=[DataRequired(), Email()])
  password = PasswordField('Password', validators=[DataRequired()])
  remember = BooleanField('Remember Me')
  submit = SubmitField('Login')     

capp/users/__init__.py
#

capp/users/routes.py
from flask import render_template, Blueprint, redirect, flash, url_for, request
from capp.users.forms import RegistrationForm, LoginForm
from capp.models import User
from capp import db, bcrypt
from flask_login import login_user, current_user, logout_user

users=Blueprint('users',__name__)

@users.route('/register', methods=['GET','POST'])
def register():
  form = RegistrationForm()
  if current_user.is_authenticated:
        return redirect(url_for('home.home_home'))
  if form.validate_on_submit():
      user_hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
      user = User(username=form.username.data, email=form.email.data, password=user_hashed_password)
      db.session.add(user)
      db.session.commit()
      flash('Your account has been created! Now, you are able to login!', 'success')
      return redirect(url_for('users.login'))
  return render_template('users/register.html', title='register', form=form)

@users.route('/login', methods=['GET','POST'])
def login():
  form = LoginForm()
  if current_user.is_authenticated:
        return redirect(url_for('users.user_profile'))
  if form.validate_on_submit():
    user = User.query.filter_by(email=form.email.data).first()
    if user and bcrypt.check_password_hash(user.password, form.password.data):
        login_user(user, remember=form.remember.data)
        next_page = request.args.get('next')
        flash('You have logged in! Now, you can start to use our Carbon App!', 'success')
        return redirect(next_page) if next_page else redirect(url_for('home.home_home'))
    else:
        flash('Login Unsuccessful. Please check email and password!', 'danger') 
  return render_template('users/login.html', title='login', form=form)

@users.route('/profile')
def user_profile():
    return render_template('users/user_profile.html')

@users.route('/logout')
def logout():    
    logout_user()
    return redirect(url_for('home.home_home'))

capp/templates/users/login.html
{% extends "layout.html" %}
{% block content %}

<section class="register_section_css">
  <div class="container">
          <div class="box">
              {% with messages = get_flashed_messages(with_categories=true) %}
                  {% if messages %}
                      {% for category, message in messages %}
                          <div class="alert alert-{{ category }}">
                              {{ message }}
                          </div> 
                      {% endfor %}
                  {% endif %}
              {% endwith %}
              <form method="POST" action="">
                  {{ form.hidden_tag() }}
                      <fieldset class="form-group">
                          <legend class="border-bottom mb-4">Log in</legend>
                          <div class="form-group">
                              {{ form.email.label(class="form-control-label") }}
                              {% if form.email.errors %}
                                  {{ form.email(class="form-control form-control-lg is-invalid") }}
                                  <div class="invalid-feedback">
                                      {% for error in form.email.errors %}
                                          <span>{{ error }}</span>
                                      {% endfor %}
                                  </div>
                              {% else %}
                                  {{ form.email(class="form-control form-control-lg") }}
                              {% endif %}
                          </div>
                          <div class="form-group">
                              {{ form.password.label(class="form-control-label") }}
                              {% if form.password.errors %}
                                  {{ form.password(class="form-control form-control-lg is-invalid") }}
                                  <div class="invalid-feedback">
                                      {% for error in form.password.errors %}
                                          <span>{{ error }}</span>
                                      {% endfor %}
                                  </div>
                              {% else %}
                                  {{ form.password(class="form-control form-control-lg") }}
                              {% endif %}
                          </div>
                          <div class="form-check">
                              {{ form.remember(class="form-check-input",style="text-align: left;") }}
                              {{ form.remember.label(class="form-check-label",style="text-align: left;") }}
                          </div>
                      </fieldset>
                      </br>
                      <div class="form-group">
                          {{ form.submit(class="cta_form") }}
                      </div>
              </form>
              </br>
              <div class="border-top pt-3">
                  <small>
                      Need an account? <a class="ml-2" href="{{ url_for('users.register') }}">Register</a>
                  </small>
              </div>

          </div>
  </div>
</section>

        
{% endblock content %}

capp/templates/users/register.html
{% extends "layout.html" %}
{% block content %}

<section class="register_section_css">
    <div class="container">
            <div class="box">
                <form method="POST" action="">
                    {{ form.hidden_tag() }}
                    <fieldset class="form-group">
                        <legend class="border-bottom mb-4">Join us now</legend>
                        <div class="form-group">
                            {{ form.username.label(class="form-control-label") }}
                            {% if form.username.errors %}
                                {{ form.username(class="form-control form-control-lg is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.username.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.username(class="form-control form-control-lg") }}
                            {% endif %}
                        </div>
                        <div class="form-group">
                            {{ form.email.label(class="form-control-label") }}
                            {% if form.email.errors %}
                                {{ form.email(class="form-control form-control-lg is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.email.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.email(class="form-control form-control-lg") }}
                            {% endif %}
                        </div>
                        <div class="form-group">
                            {{ form.password.label(class="form-control-label") }}
                            {% if form.password.errors %}
                                {{ form.password(class="form-control form-control-lg is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.password.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.password(class="form-control form-control-lg") }}
                            {% endif %}
                        </div>
                        <div class="form-group">
                            {{ form.confirm_password.label(class="form-control-label") }}
                            {% if form.confirm_password.errors %}
                                {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.confirm_password.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.confirm_password(class="form-control form-control-lg") }}
                            {% endif %}
                        </div>
                    </fieldset>
                    </br>
                    <div class="form-group">
                        {{ form.submit(class="cta_form") }}
                    </div>
                </form>
                </br>
                <div class="border-top pt-3">
                    <small>
                        Already have an account? <a class="ml-5" href="{{ url_for('users.login') }}">Sign in</a>
                    </small>
                </div>

            </div>
    </div>
</section>

        
{% endblock content %}

capp/templates/users/user_profile.html
{% extends "layout.html" %} {% block content %} 

{% if current_user.is_authenticated %}
<div class="profile">
<h1>Hi {{ current_user.username }}, here are your profile details:</h1>
<br />
{{ current_user.email }}
<br />
<br />
<p>
  Do you need to logout? Then click here:
  <a href="{{url_for('users.logout')}}">logout</a>.
</p>
</div>

{% else %}

<h1>
  You don't have a profile yet. Create one here:
  <a href="{{url_for('users.register')}}">Register</a>
</h1>

{% endif %} {% endblock content %}