capp/carbon_app/routes.py
from flask import render_template, Blueprint, request, redirect, url_for, flash
from capp.models import Transport
from capp import db
from datetime import timedelta, datetime
from flask_login import login_required, current_user
from capp.carbon_app.forms import BusForm, CarForm, PlaneForm, FerryForm, MotorbikeForm, BicycleForm, WalkForm
import json

carbon_app=Blueprint('carbon_app',__name__)

#Emissions factor per transport in kg per passemger km
#Data from: http://efdb.apps.eea.europa.eu/?source=%7B%22query%22%3A%7B%22match_all%22%3A%7B%7D%7D%2C%22display_type%22%3A%22tabular%22%7D
efco2={'Bus':{'Diesel':0.10231,'CNG':0.08,'Petrol':0.10231,'No Fossil Fuel':0},
    'Car':{'Petrol':0.18592,'Diesel':0.16453,'No Fossil Fuel':0},
    'Plane':{'Petrol':0.24298},
    'Ferry':{'Diesel':0.11131, 'CNG':0.1131, 'No Fossil Fuel':0},
    'Motorbike':{'Petrol':0.09816,'No Fossil Fuel':0},
    'Scooter':{'No Fossil Fuel':0},
    'Bicycle':{'No Fossil Fuel':0},
    'Walk':{'No Fossil Fuel':0}}
efch4={'Bus':{'Diesel':2e-5,'CNG':2.5e-3,'Petrol':2e-5,'No Fossil Fuel':0},
    'Car':{'Petrol':3.1e-4,'Diesel':3e-6,'No Fossil Fuel':0},
    'Plane':{'Petrol':1.1e-4},
    'Ferry':{'Diesel':3e-5, 'CNG':3e-5,'No Fossil Fuel':0},
    'Motorbike':{'Petrol':2.1e-3,'No Fossil Fuel':0},
    'Scooter':{'No Fossil Fuel':0},
    'Bicycle':{'No Fossil Fuel':0},
    'Walk':{'No Fossil Fuel':0}}

#Carbon app, main page
@carbon_app.route('/carbon_app')
@login_required
def carbon_app_home():
    return render_template('carbon_app/carbon_app.html', title='carbon_app')

#New entry bus
@carbon_app.route('/carbon_app/new_entry_bus', methods=['GET','POST'])
@login_required
def new_entry_bus():
    form = BusForm()
    if form.validate_on_submit():
        kms = form.kms.data
        fuel = form.fuel_type.data
        transport = 'Bus'
        # kms = request.form['kms']
        # fuel = request.form['fuel_type']

        co2 = float(kms) * efco2[transport][fuel]
        ch4 = float(kms) * efch4[transport][fuel]
        total = co2+ch4

        co2 = float("{:.2f}".format(co2))
        ch4 = float("{:.2f}".format(ch4))
        total = float("{:.2f}".format(total))

        emissions = Transport(kms=kms, transport=transport, fuel=fuel, co2=co2, ch4=ch4, total=total, author=current_user)
        db.session.add(emissions)
        db.session.commit()
        return redirect(url_for('carbon_app.your_data'))
    return render_template('carbon_app/new_entry_bus.html', title='new entry bus', form=form)

#New entry car
@carbon_app.route('/carbon_app/new_entry_car', methods=['GET','POST'])
@login_required
def new_entry_car():
    form = CarForm()
    if form.validate_on_submit():
        kms = form.kms.data
        fuel = form.fuel_type.data
        transport = 'Car'
        # kms = request.form['kms']
        # fuel = request.form['fuel_type']

        co2 = float(kms) * efco2[transport][fuel]
        ch4 = float(kms) * efch4[transport][fuel]
        total = co2+ch4

        co2 = float("{:.2f}".format(co2))
        ch4 = float("{:.2f}".format(ch4))
        total = float("{:.2f}".format(total))

        emissions = Transport(kms=kms, transport=transport, fuel=fuel, co2=co2, ch4=ch4, total=total, author=current_user)
        db.session.add(emissions)
        db.session.commit()
        return redirect(url_for('carbon_app.your_data'))
    return render_template('carbon_app/new_entry_car.html', title='new entry car', form=form)    

#New entry plane
@carbon_app.route('/carbon_app/new_entry_plane', methods=['GET','POST'])
@login_required
def new_entry_plane():
    form = PlaneForm()
    if form.validate_on_submit():
        kms = form.kms.data
        fuel = form.fuel_type.data
        transport = 'Plane'
        # kms = request.form['kms']
        # fuel = request.form['fuel_type']

        co2 = float(kms) * efco2[transport][fuel]
        ch4 = float(kms) * efch4[transport][fuel]
        total = co2+ch4

        co2 = float("{:.2f}".format(co2))
        ch4 = float("{:.2f}".format(ch4))
        total = float("{:.2f}".format(total))

        emissions = Transport(kms=kms, transport=transport, fuel=fuel, co2=co2, ch4=ch4, total=total, author=current_user)
        db.session.add(emissions)
        db.session.commit()
        return redirect(url_for('carbon_app.your_data'))
    return render_template('carbon_app/new_entry_plane.html', title='new entry plane', form=form)  

#New entry ferry
@carbon_app.route('/carbon_app/new_entry_ferry', methods=['GET','POST'])
@login_required
def new_entry_ferry():
    form = FerryForm()
    if form.validate_on_submit():
        kms = form.kms.data
        fuel = form.fuel_type.data
        transport = 'Ferry'
        # kms = request.form['kms']
        # fuel = request.form['fuel_type']

        co2 = float(kms) * efco2[transport][fuel]
        ch4 = float(kms) * efch4[transport][fuel]
        total = co2+ch4

        co2 = float("{:.2f}".format(co2))
        ch4 = float("{:.2f}".format(ch4))
        total = float("{:.2f}".format(total))

        emissions = Transport(kms=kms, transport=transport, fuel=fuel, co2=co2, ch4=ch4, total=total, author=current_user)
        db.session.add(emissions)
        db.session.commit()
        return redirect(url_for('carbon_app.your_data'))
    return render_template('carbon_app/new_entry_ferry.html', title='new entry ferry', form=form)     

#New entry motorbike
@carbon_app.route('/carbon_app/new_entry_motorbike', methods=['GET','POST'])
@login_required
def new_entry_motorbike():
    form = MotorbikeForm()
    if form.validate_on_submit():
        kms = form.kms.data
        fuel = form.fuel_type.data
        transport = 'Motorbike'
        # kms = request.form['kms']
        # fuel = request.form['fuel_type']

        co2 = float(kms) * efco2[transport][fuel]
        ch4 = float(kms) * efch4[transport][fuel]
        total = co2+ch4

        co2 = float("{:.2f}".format(co2))
        ch4 = float("{:.2f}".format(ch4))
        total = float("{:.2f}".format(total))

        emissions = Transport(kms=kms, transport=transport, fuel=fuel, co2=co2, ch4=ch4, total=total, author=current_user)
        db.session.add(emissions)
        db.session.commit()
        return redirect(url_for('carbon_app.your_data'))
    return render_template('carbon_app/new_entry_motorbike.html', title='new entry motorbike', form=form) 

#New entry bicycle
@carbon_app.route('/carbon_app/new_entry_bicycle', methods=['GET','POST'])
@login_required
def new_entry_bicycle():
    form = BicycleForm()
    if form.validate_on_submit():
        kms = form.kms.data
        fuel = form.fuel_type.data
        transport = 'Bicycle'
        # kms = request.form['kms']
        # fuel = request.form['fuel_type']

        co2 = float(kms) * efco2[transport][fuel]
        ch4 = float(kms) * efch4[transport][fuel]
        total = co2+ch4

        co2 = float("{:.2f}".format(co2))
        ch4 = float("{:.2f}".format(ch4))
        total = float("{:.2f}".format(total))

        emissions = Transport(kms=kms, transport=transport, fuel=fuel, co2=co2, ch4=ch4, total=total, author=current_user)
        db.session.add(emissions)
        db.session.commit()
        return redirect(url_for('carbon_app.your_data'))
    return render_template('carbon_app/new_entry_bicycle.html', title='new entry bicycle', form=form)

#New entry walk
@carbon_app.route('/carbon_app/new_entry_walk', methods=['GET','POST'])
@login_required
def new_entry_walk():
    form = WalkForm()
    if form.validate_on_submit():
        kms = form.kms.data
        fuel = form.fuel_type.data
        transport = 'Walk'
        # kms = request.form['kms']
        # fuel = request.form['fuel_type']

        co2 = float(kms) * efco2[transport][fuel]
        ch4 = float(kms) * efch4[transport][fuel]
        total = co2+ch4

        co2 = float("{:.2f}".format(co2))
        ch4 = float("{:.2f}".format(ch4))
        total = float("{:.2f}".format(total))

        emissions = Transport(kms=kms, transport=transport, fuel=fuel, co2=co2, ch4=ch4, total=total, author=current_user)
        db.session.add(emissions)
        db.session.commit()
        return redirect(url_for('carbon_app.your_data'))
    return render_template('carbon_app/new_entry_walk.html', title='new entry walk', form=form)

#Your data
@carbon_app.route('/carbon_app/your_data')
@login_required
def your_data():
    #Table
    entries = Transport.query.filter_by(author=current_user). \
        filter(Transport.date> (datetime.now() - timedelta(days=5))).\
        order_by(Transport.date.desc()).order_by(Transport.transport.asc()).all()
    
    #Emissions by category
    emissions_by_transport = db.session.query(db.func.sum(Transport.total), Transport.transport). \
        filter(Transport.date > (datetime.now() - timedelta(days=5))).filter_by(author=current_user). \
        group_by(Transport.transport).order_by(Transport.transport.asc()).all()
    emission_transport = [0, 0, 0, 0, 0, 0, 0, 0]
    first_tuple_elements = []
    second_tuple_elements = []
    for a_tuple in emissions_by_transport:
        first_tuple_elements.append(a_tuple[0])
        second_tuple_elements.append(a_tuple[1])

    if 'Bus' in second_tuple_elements:
        index_bus = second_tuple_elements.index('Bus')
        emission_transport[1]=first_tuple_elements[index_bus]
    else:
        emission_transport[1]

    if 'Car' in second_tuple_elements:
        index_car = second_tuple_elements.index('Car')
        emission_transport[2]=first_tuple_elements[index_car]
    else:
        emission_transport[2]

    if 'Ferry' in second_tuple_elements:
        index_ferry = second_tuple_elements.index('Ferry')
        emission_transport[3]=first_tuple_elements[index_ferry]
    else:
        emission_transport[3]

    if 'Motorbike' in second_tuple_elements:
        index_motorbike = second_tuple_elements.index('Motorbike')
        emission_transport[4]=first_tuple_elements[index_motorbike]
    else:
        emission_transport[4]

    if 'Plane' in second_tuple_elements:

capp/home/__init__.py
#

capp/home/routes.py
from flask import render_template, Blueprint


home=Blueprint('home',__name__)

@home.route('/')
@home.route('/home')
def home_home():
  return render_template('home.html')

capp/methodology/__init__.py
#

capp/methodology/routes.py
from flask import render_template, Blueprint

methodology=Blueprint('methodology',__name__)

@methodology.route('/methodology')
def methodology_home():
  return render_template('methodology.html', title='methodology')

capp/users/routes.py
from flask import render_template, Blueprint, redirect, flash, url_for, request
from capp.users.forms import RegistrationForm, LoginForm
from capp.models import User
from capp import db, bcrypt
from flask_login import login_user, current_user, logout_user

users=Blueprint('users',__name__)

@users.route('/register', methods=['GET','POST'])
def register():
  form = RegistrationForm()
  if current_user.is_authenticated:
        return redirect(url_for('home.home_home'))
  if form.validate_on_submit():
      user_hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
      user = User(username=form.username.data, email=form.email.data, password=user_hashed_password)
      db.session.add(user)
      db.session.commit()
      flash('Your account has been created! Now, you are able to login!', 'success')
      return redirect(url_for('users.login'))
  return render_template('users/register.html', title='register', form=form)

@users.route('/login', methods=['GET','POST'])
def login():
  form = LoginForm()
  if current_user.is_authenticated:
        return redirect(url_for('users.user_profile'))
  if form.validate_on_submit():
    user = User.query.filter_by(email=form.email.data).first()
    if user and bcrypt.check_password_hash(user.password, form.password.data):
        login_user(user, remember=form.remember.data)
        next_page = request.args.get('next')
        flash('You have logged in! Now, you can start to use our Carbon App!', 'success')
        return redirect(next_page) if next_page else redirect(url_for('home.home_home'))
    else:
        flash('Login Unsuccessful. Please check email and password!', 'danger') 
  return render_template('users/login.html', title='login', form=form)

@users.route('/profile')
def user_profile():
    return render_template('users/user_profile.html')

@users.route('/logout')
def logout():    
    logout_user()
    return redirect(url_for('home.home_home'))

capp/templates/home.html
{% extends "layout.html" %} {% block content %}

<div class="container">
  <div class="left-block">
    <!-- SECTION 1 -->
    {% if current_user.is_authenticated %}
    <h1>{{ current_user.username }}, reduce your carbon footprint with EcoPaths</h1>
    {% else %}
    <h1>Reduce your carbon footprint with EcoPaths</h1>
    {% endif %}
    <p>
      Our app was meticulously crafted with the intention of aiding individuals
      in lessening their carbon footprint effortlessly. It serves as a
      convenient tool for calculating carbon emissions, presenting users with a
      comprehensive overview derived from their input data.
    </p>
    <a href="{{url_for('users.register')}}" class="cta">I want to try</a>
  </div>

  <div class="right-block">
    <img
      src="{{url_for('static', filename='icons/forestpath.jpg')}}"
      class="forestpath"
      alt="Path in the forest"
    />
  </div>
</div>

<!-- SECTION 2 -->
<div class="container">
  <div class="right-block">
    <img
      src="{{url_for('static', filename='icons/earthstorm.jpg')}}"
      class="forestpath"
      alt="Earth with thunder storm"
    />
  </div>

  <div class="left-block">
    <!-- Header -->
    <h1>The problem of carbon emissions</h1>
    <p>
      As greenhouse gases envelop the Earth, they act like a thick blanket,
      trapping the sun's heat and causing temperatures to rise globally. This
      phenomenon, known as global warming, is driving significant changes in our
      climate patterns. Alarmingly, the pace of this warming exceeds any
      observed in recorded history.
    </p>
    <a href="{{url_for('carbon_app.carbon_app_home')}}" class="cta">The solution</a>
  </div>
</div>

<!-- Developers -->

<section class="dev_section">
  <div class="dev_blocks">
    <div class="dev_pic">
      <img
        src="{{url_for('static', filename='icons/sacha.jpg')}}"
        class="dev_img"
        alt="Developer Sacha"
      />
      <div class="dev_linkedin">
        <a href="https://www.linkedin.com/in/sacha-van-cauwenbergh/" target="_blank">
          <i class="fa-brands fa-linkedin fa-2xl"></i>
        </a>
      </div>
      <h4 class="dev_name">Sacha</h4>
    </div>
  </div>
  <div class="dev_blocks">
    <div class="dev_pic">
      <img
        src="{{url_for('static', filename='icons/mar.jpg')}}"
        class="dev_img"
        alt="Developer Mar"
      />
      <div class="dev_linkedin">
        <a href="https://www.linkedin.com/in/maría-del-mar-lópez-urquiola" target="_blank">
          <i class="fa-brands fa-linkedin fa-2xl"></i>
        </a>
      </div>
      <h4 class="dev_name">Mar</h4>
    </div>
  </div>
  <div class="dev_blocks">
    <div class="dev_pic">
      <img
        src="{{url_for('static', filename='icons/antoine.jpg')}}"
        class="dev_img"
        alt="Developer Antoine"
      />
      <div class="dev_linkedin">
        <a href="https://www.linkedin.com/in/antoine-senger-6aba94224/" target="_blank">
          <i class="fa-brands fa-linkedin fa-2xl"></i>
        </a>
      </div>
      <h4 class="dev_name">Antoine</h4>
    </div>
  </div>
  <div class="dev_blocks">
    <div class="dev_pic">
      <img
        src="{{url_for('static', filename='icons/sara.jpg')}}"
        class="dev_img"
        alt="Developer Sara"
      />
      <div class="dev_linkedin">
        <a href="www.linkedin.com/in/sara-rorato-9933a72b9" target="_blank">
          <i class="fa-brands fa-linkedin fa-2xl"></i>
        </a>
      </div>
      <h4 class="dev_name">Sara</h4>
    </div>
  </div>
  <div class="dev_blocks">
    <div class="dev_pic">
      <img
        src="{{url_for('static', filename='icons/marine.jpg')}}"
        class="dev_img"
        alt="Developer Marine"
      />
      <div class="dev_linkedin">
        <a href="https://www.linkedin.com/in/marine-croze-554a97192/" target="_blank">
          <i class="fa-brands fa-linkedin fa-2xl"></i>
        </a>
      </div>
      <h4 class="dev_name">Marine</h4>
    </div>
  </div>
</section>

<!-- Methodlogy-->

<div class="container">
  <div class="methodology_container">
  <p>
    <a href="{{url_for('methodology.methodology_home')}}">The methodology page</a>
    <br />
    <br />
    Discover the backbone of our Carbon App's functionality by exploring our
    detailed methodology page. This page offers an insightful look into the
    rigorous process behind our carbon emissions calculations. Delve into the
    scientific foundations underpinning our methodology, from the collection of
    real-world data to the development of intricate formulas. By visiting this
    page, you'll gain a deeper understanding of your daily carbon emissions and
    the pivotal role you play in combating climate change.
  </p>
  </div>
</div>

{% endblock content %}

capp/templates/layout.html
<!DOCTYPE html>
<html>
  <head>
    <!-- Font Awesome code -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"
      integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />

    <!--Import the Bootstrap CSS file -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css"
    />

    <!-- CSS code -->
    <link
      rel="stylesheet"
      type="text/css"
      href="{{ url_for('static', filename='layout.css') }}"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{{ url_for('static', filename='home.css') }}"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{{ url_for('static', filename='cursor.css') }}"
    />
    

    <!-- To activate media queries in devices -->
    <meta
      name="viewport"
      content="user-scalable=yes, width=device-width, initial-scale=1"
    />

    <!-- MathJax -->
    <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
    <script
      id="MathJax-script"
      async
      src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
    ></script>

    <!-- ChartsJS -->
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>

    {% if title %}
    <title>{{ title }}</title>
    {% else %}
    <title>home</title>
    {% endif %}
  </head>
  <body>
    <div class="animated-dot"></div>
    <section class="navbar">
      <div class="container">
        <a href="{{url_for('home.home_home')}}">
          <img
            src="{{url_for('static', filename='icons/ecopaths_logo.svg')}}"
            class="logo"
            alt="Logo EcoPaths"
          />
        </a>
        {% if current_user.is_authenticated %}
        <nav>
          <ul>
            <li>
              <a href="{{ url_for('home.home_home') }}">Home</a>
            </li>
            <li>
              <a href="{{url_for('methodology.methodology_home')}}"
                >Methodology</a
              >
            </li>
            <li>
              <a href="{{url_for('carbon_app.carbon_app_home')}}">Carbon App</a>
            </li>
            <li>
              <a href="{{url_for('users.user_profile')}}">My account</a>
            </li>
          </ul>
        </nav>
        {% else %}
        <nav>
          <ul>
            <li>
              <a href="{{ url_for('home.home_home') }}">Home</a>
            </li>
            <li>
              <a href="{{url_for('methodology.methodology_home')}}"
                >Methodology</a
              >
            </li>
            <li>
              <a href="{{url_for('carbon_app.carbon_app_home')}}">Carbon App</a>
            </li>
            <li>
              <a href="{{url_for('users.register')}}">Create account</a>
            </li>
          </ul>
        </nav>
        {% endif %}
      </div>
    </section>

    {% block content %} {% endblock %}

    <section class="footer">
      <div class="footer_back">
        <div class="footer_cta">
          <h2>Create your account now</h2>
          <a href="{{url_for('users.register')}}" class="cta">Register</a>
        </div>

        <div class="footer-content">
          <div class="footer-menu">
            <nav>
              <ul>
                <li>
                  <a href="{{ url_for('home.home_home') }}">Home</a>
                </li>
                <li>
                  <a href="{{url_for('methodology.methodology_home')}}"
                    >Methodology</a
                  >
                </li>
                <li>
                  <a href="{{url_for('carbon_app.carbon_app_home')}}"
                    >Carbon App</a
                  >
                </li>
                <li>
                  <a href="{{url_for('users.register')}}">Account</a>
                </li>
              </ul>
            </nav>
          </div>

          <div class="footer-disclaimer">
            <p>
              Please note that the Carbon App is a student project developed as
              part of an educational aim.
            </p>
          </div>

          <div class="footer-logos">
            <a href="https://www.instagram.com/eco_paths/" target="_blank">
              <i class="fa-brands fa-square-instagram fa-3x"></i>
            </a>
            <a
              href="https://www.facebook.com/profile.php?id=61556825853040"
              target="_blank"
            >
              <i class="fa-brands fa-square-facebook fa-3x"></i>
            </a>
          </div>
        </div>
      </div>
    </section>
    <!-- Javascript -->
    <script src="{{ url_for('static', filename='myscripts.js') }}"></script>
  </body>
</html>